### ISSUE TITLE
I cant save my world

### ISSUE THREAD

**Issue by KillerJWB86** [cokolele/terraria-map-editor#3]
I go to https://www.terraria-map-editor.eu/ and load up my world but i cant save it after. Its a 1.4 world. Is there something else i have to do the be able to?

**Comment by cokolele** [comment]
![Read carefully](https://user-images.githubusercontent.com/26676195/82340245-4c9fdc80-99ef-11ea-982a-951a4ae4d998.png)

I have to update saving library first, but i don't have a lot of time now. Should be in a week or so.
