### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RazorManager89** [cokolele/terraria-map-editor#4]
`Object { name: "TypeError", message: "t is undefined", onlyMessage: undefined, stack: "S@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:7524\ne/<@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:9105\nh@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:200:966\nu/i._invoke</<@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:200:755\nE/</t[r]@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:200:1388\nE@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:2689\ni@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:2892\nb/</<@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:2951\nb/<@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:2832\nparcelRequire<.yGf6</self.onmessage</<@https://www.terraria-map-editor.eu/web-worker.8eaefb46.js:275:9528\n" }`

**Comment by cokolele** [comment]
New parsing broke map saving for 1.3.5.3, which worked before. I'm gonna try to build and old version

**Comment by cokolele** [comment]
[Final version of the project for 1.3.5.3 is up and running](https://www.terraria-map-editor.com/version/1.final/)
