### ISSUE TITLE
Terraria mobile worlds compatibility

### ISSUE THREAD

**Issue by jbro129** [cokolele/terraria-map-editor#6]
Mobile Terraria Worlds as of v1.3.0.7.9 is has the same world header and structure of PC 1.3 worlds and I see your site only supports 1.3.6 and above.
TEdit v3.6 can parse mobile 1.3 worlds like it would for PC 1.3 worlds in case you think that the wld files are structured differently.
Mobile worlds use world version 155.
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/3.6.16126.20

Can you add compatibility to Terraria 1.3 worlds? It would allow mobile users to edit their worlds without needing to use an older version of TEdit or need a computer at all.

Thank you!

**Comment by cokolele** [comment]
I will check it out. I know that Tedit has some backwards compatibility checks for much older map versions than this project, and i do not plan on adding them that soon.

Anyway, i will check the mobile version files and if the structure is the same i could make "Bad map version" error just a warning, not fatal one.

**Comment by cokolele** [comment]
Terraria mobile app was updated to 1.4
